# Our stages
stages:
  - build

# Build WordPress plugin file
build:
  stage: build
  only:
    - /gitlab-ci/
  tags:
    - docker
  image: node:12
  script:
    - npm --prefix plugins/plenamata/ install
    - npm --prefix plugins/plenamata/ run build:production
    - apt update && apt install -y zip unzip
    - cd plugins && zip -r --exclude="*node_modules*" --exclude="*vendor*" /plenamata-plugin.zip plenamata/
  artifacts:
    paths:
      - /plenamata-plugin.zip
    expire_in: 1 week
