# Our stages
stages:
  - build
  - deploy
variables:
  KUBECONFIG: /etc/k8s-config

# Build WordPress plugin file
build:
  stage: build
  only:
    - /gitlab-ci/
  tags:
    - docker
  image: node:12
  script:
    - npm --prefix plugins/plenamata/ install
    - npm --prefix plugins/plenamata/ run build:production
    - apt update && apt install -y zip unzip
    - cd plugins && zip -r --exclude="*node_modules*" --exclude="*vendor*" plenamata-plugin.zip plenamata/
  artifacts:
    paths:
      - plugins/plenamata-plugin.zip
      - plugins/plenamata
    expire_in: 1 week


deploy:
  stage: deploy
  image: hacklab/kubectl:latest
  script:
    - echo ${kubeconfig} | base64 -d > ${KUBECONFIG}
    - kubectl cp plugins/plenamata-plugin.zip plenamata-site-dev/$(kubectl get pods -n plenamata-site-dev | grep wordpress | cut -d ' ' -f 1):/var/www/html/plugins/plenamata/
  only:
    - /gitlab-ci/
  tags:
    - docker