# Our stages
stages:
  - build_composer
  - build_assets
  - deploy
variables:
  KUBECONFIG: /etc/k8s-config


build_composer:
  stage: build_composer
  only:
    - /master/
  tags:
    - docker
  image: composer:2.1.5
  script:
    - composer build --working-dir=./plugins/plenamata-plugin/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - plugins/plenamata-plugin/vendor/
      - plugins/plenamata-plugin/vendor_prefixed/
    
build_assets:
  stage: build_assets
  only:
    - /master/
  tags:
    - docker
  image: node:12
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - plugins/plenamata-plugin/vendor/
      - plugins/plenamata-plugin/vendor_prefixed/
      - plugins/plenamata-plugin/assets/build
    
  script:
    - npm --prefix plugins/plenamata-plugin/ install
    - npm --prefix plugins/plenamata-plugin/ run build:production
    - rm -rf plugins/plenamata-plugin/node_modules
  artifacts:
    paths:
      - plugins/plenamata-plugin/*
    name: plenamata-plugin.zip
    expire_in: 1 week


deploy:
  stage: deploy
  image: hacklab/kubectl:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - plugins/plenamata-plugin/vendor/
      - plugins/plenamata-plugin/vendor_prefixed/
      - plugins/plenamata-plugin/assets/build
  script:
    - echo ${kubeconfig} | base64 -d > ${KUBECONFIG}
    - kubectl cp "plugins/plenamata-plugin" plenamata-site-dev/$(kubectl get pods -n plenamata-site-dev | grep wordpress | cut -d ' ' -f 1):"/var/www/html/wp-content/plugins/"
    - kubectl exec -n plenamata-site-dev -it $(kubectl get pods -n plenamata-site-dev | grep wordpress | cut -d ' ' -f 1) -- sh -c "chown -R www-data /var/www/html/wp-content/plugins/plenamata-plugin && chgrp -R www-data /var/www/html/wp-content/plugins/plenamata-plugin" 
  only:
    - /master/
  tags:
    - docker