# Our stages
stages:
  - build_composer
  - build_assets
  - deploy
variables:
  KUBECONFIG: /etc/k8s-config

build_composer:
  stage: build_composer
  only:
    - /gitlab-ci/
  tags:
    - docker
  image: composer:2.1.5
  script:
    - composer install --working-dir=./plugins/plenamata-plugin/
    
build_assets:
  stage: build_assets
  only:
    - /gitlab-ci/
  tags:
    - docker
  image: node:12
  script:
    - npm --prefix plugins/plenamata-plugin/ install
    - npm --prefix plugins/plenamata-plugin/ run build:production
    - apt update && apt install -y zip unzip
    - rm -rf plugins/plenamata-plugin/node_modules
  artifacts:
    paths:
      - plugins/plenamata-plugin/*
    name: plenamata-plugin.zip
    expire_in: 1 week


deploy:
  stage: deploy
  image: hacklab/kubectl:latest
  script:
    - echo ${kubeconfig} | base64 -d > ${KUBECONFIG}
    - kubectl cp "plugins/plenamata-plugin/" plenamata-site-dev/$(kubectl get pods -n plenamata-site-dev | grep wordpress | cut -d ' ' -f 1):"/var/www/html/wp-content/plugins/"
  only:
    - /gitlab-ci/
  tags:
    - docker